Homework tms/hometask 12
Vagazzi/Homework_TMS pull request #16
Opened 2023-05-14 10:36 UTC by Vagazzi

2023-05-14 20:16 UTC, Pavel-Tsishkevich requested changes

2023-05-14 20:16 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/twelveth/TwelvethHometask.java
> +        List<String> wordList = new ArrayList<>(Arrays.stream(initialString.split(" ")).toList());
Вадим, стримы это не затычка всех дыр в джава. их нужно использовать с толком, и вот лично тут он вот даром не нужен

2023-05-14 20:16 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/twelveth/TwelvethHometask.java
> +        new LinkedHashSet<>(result).forEach(log::info);
ох боже, зачем тебе линкед хэш сет? только честно)

2023-05-14 20:16 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/twelveth/TwelvethHometask.java
> +    public void thirdTask() {
смотри, в этом решении мне не нравится несколько вещей: 1) то, что листы лежат непонятно где, 2) то, что если ты два раза запустишь этот метод ты сильно удивишься результатам), 3) что ты значения пихаешь в конкретные листы а не мапку, ну и что каунтер лежит вне трая, а используется только внутри трая

2023-05-14 20:43 UTC, Vagazzi commented on src/main/java/org/example/homework/twelveth/TwelvethHometask.java
> +        new LinkedHashSet<>(result).forEach(log::info);
Тут я хотел порядок добавления в коллекцию сохранить

2023-05-14 21:05 UTC, Vagazzi commented on src/main/java/org/example/homework/twelveth/TwelvethHometask.java
> +        List<String> wordList = new ArrayList<>(Arrays.stream(initialString.split(" ")).toList());
А тут, как мне показалось, наиболее читаемый вариант для сплита строки и дальнейшего каста её же в ArrayList<>()

2023-05-15 08:29 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/twelveth/TwelvethHometask.java
> +        List<String> wordList = new ArrayList<>(Arrays.stream(initialString.split(" ")).toList());
самый читаемый вариант здесь List<String> wordList = Arrays.asList(initialString.split(" "));

2023-05-15 08:30 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/twelveth/TwelvethHometask.java
> +        new LinkedHashSet<>(result).forEach(log::info);
а зачем?)

2023-05-19 10:45 UTC, merged