solved 13th hometask
Vagazzi/Homework_TMS pull request #18
Opened 2023-05-19 16:58 UTC by Vagazzi

2023-05-21 19:54 UTC, Pavel-Tsishkevich requested changes

2023-05-21 19:54 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/thirteenth/ThirteenthHomeTask.java
> +    private static void getDayOfWeekByInputtedDate() {
Вадим, не может войд метод называться со слова гет, он ничего по умолчанию не может вернуть

2023-05-21 19:54 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/thirteenth/ThirteenthHomeTask.java
> +            log.info("Enter the day");
странный способ задавать дату) в классе будешь покажу как проще

2023-05-21 19:54 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/thirteenth/ThirteenthHomeTask.java
> +        Function<String, Integer> highCaseLetters = (string) -> {
а что ты тут считаешь?) по условию были гласные буквы, а тут непонятно что, видимо просто количество букв

2023-05-21 19:54 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/thirteenth/ThirteenthHomeTask.java
> +            } else return second;
а зачем тут елсе?)

2023-05-28 19:27 UTC, Pavel-Tsishkevich requested changes

2023-05-28 19:27 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/thirteenth/ThirteenthHomeTask.java
> +            Pattern vocals = Pattern.compile("(?iu)[aeiouy]");
не совсем понимаю паттерн, что значит (?iu)?

2023-05-29 00:17 UTC, Vagazzi commented on src/main/java/org/example/homework/thirteenth/ThirteenthHomeTask.java
> +            Pattern vocals = Pattern.compile("(?iu)[aeiouy]");
case-insensitive и unicode case.
https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
https://ru.stackoverflow.com/a/642118

2023-05-29 12:50 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/thirteenth/ThirteenthHomeTask.java
> +            Pattern vocals = Pattern.compile("(?iu)[aeiouy]");
уф, проще было бы саму строку toLowerCase сделать

2023-05-29 12:51 UTC, Pavel-Tsishkevich approved these changes

2023-05-29 16:43 UTC, merged