Hometask 3
Vagazzi/Homework_TMS pull request #2
Opened 2023-03-30 19:21 UTC by Vagazzi

2023-03-30 19:22 UTC, Vagazzi commented
код ревью сам себя не сделает

2023-03-30 19:23 UTC, Vagazzi commented on src/main/java/org/example/Main.java
> +//        int[] firstArrayForComparing = new int[5];
Вот эти комменты я удалил в следующем коммите.

2023-03-31 06:31 UTC, Pavel-Tsishkevich requested changes

2023-03-31 06:31 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/Main.java
> +            avgValue += j / (float) pseudoDynamicArray.length;
Смотри, вот здесь ты каждый раз конвертируешь длину в вещественное число, гораздо проще один раз перед циклом это сделать, да и есть ли смысл делить каждое число, если можно один раз поделить сумму?)

2023-03-31 06:31 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/Main.java
> +        for (int j : array) {
Вот тут проще было воспользоваться sout Arrays.toString(array)

2023-03-31 06:31 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/Main.java
> +            System.out.println(j + "\n");
Смотри, саут и так переносит на след строку, \n тут лишнее)

2023-03-31 18:26 UTC, Pavel-Tsishkevich approved these changes

2023-03-31 21:26 UTC, merged