solved hometask 4 and waiting for code review
Vagazzi/Homework_TMS pull request #3
Opened 2023-04-04 16:14 UTC by Vagazzi

2023-04-04 20:15 UTC, Pavel-Tsishkevich requested changes

2023-04-04 20:15 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/Main.java
> +        double progressy = Math.abs(lastWeight - firstWeight);
смотри, зачем тебе тут абс? чтобы потом делать иф плюс елсе минус? а почему в самом прогресси не оставить минус?

2023-04-04 20:15 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework_4/FourthHomework.java
> +        for (int i = 0; i < chessBoard.length; i++) {
как думаешь, можно ли это упростить?)

2023-04-04 20:15 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework_4/FourthHomework.java
> +    private static void printArray(String message, int[][] array) {
зачем тебе такой принт если есть метод в Arrays (deepToString)

2023-04-04 20:30 UTC, Vagazzi commented on src/main/java/org/example/homework_4/FourthHomework.java
> +    private static void printArray(String message, int[][] array) {
Так вывод красивее получается

2023-04-05 09:02 UTC, Pavel-Tsishkevich approved these changes

2023-04-05 12:25 UTC, merged