Hometask5
Vagazzi/Homework_TMS pull request #8
Opened 2023-04-06 16:52 UTC by Vagazzi

2023-04-06 16:59 UTC, Vagazzi commented
Алгоритм выдачи денег страшный до ужаса, и ничего общего с реальностью, скорее всего, не имеет, но, как говорят умные дядьки в интернете, общего решения данной проблемы не существует.

2023-04-07 07:33 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework_5/ATM.java
> +package org.example.homework_5;
я бы писал название пакета без _, или homework5 или homework.fifth

2023-04-07 07:42 UTC, Pavel-Tsishkevich requested changes

2023-04-07 07:42 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework_5/ATM.java
> +        if (initialAmountOfMoneyForWithdraw == twentyBucks || initialAmountOfMoneyForWithdraw == fiftyBucks || initialAmountOfMoneyForWithdraw == oneHundredBucks) {
вот эта штука дико неоптимальная, например - если ты в ифе кидаешь ретурн, тебе не нужен блок елсе, это будет отдельный иф

2023-04-07 07:42 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework_5/ATM.java
> +            if (initialAmountOfMoneyForWithdraw == twentyBucks) {
мне кажется вот эти ифы отлично кладутся на следующие, и что решение будет гораздо гораздо более понятным, если ты его сделаешь через циклы, к примеру while(sumOfMoney >=20). И смотри что еще мне не нравится, допустим ты ввел сумму 60 баксов, он по твоей логике выдаст тебе 50 баксов и потом скажет что-то про деньги, т.е. мне кажется надо сначала посчитать сможет ли выдать такую сумму, или сделать метод который возвращает как он может выдать такую сумму)

2023-04-07 07:42 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework_5/CreditCard.java
> +@Setter
я не уверен что ломбок будет тут работать, но если будет - то и конструкторы можно задавать через него, @NoArgsConstructor, @AllArgsConstructor

2023-04-07 07:42 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework_5/HDD.java
> +@Getter
ты тут и ломбок используешь и обычные геттеры и сеттеры, надо что-то одно)

2023-04-07 07:42 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework_5/PC.java
> +@Getter
да, и ту стринг тоже есть в ломбоке - @ToString

2023-04-09 18:51 UTC, Pavel-Tsishkevich requested changes

2023-04-09 18:51 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/fifth/typeOfStorage.java
> +public enum typeOfStorage {
Класс с маленькой назвал

2023-04-13 18:25 UTC, closed without merging