solved sixth home-task, waiting for a code review
Vagazzi/Homework_TMS pull request #9
Opened 2023-04-11 20:52 UTC by Vagazzi

2023-04-12 09:27 UTC, Pavel-Tsishkevich requested changes

2023-04-12 09:27 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/SixthHomework.java
> +        CEO.setEmployeePosition("CEO");
смотри, ты сейчас в коде говоришь СЕО, что он СЕО) как думаешь, он разве не знает?)

2023-04-12 09:27 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/SixthHomework.java
> +        dateOfDocument.set(Calendar.YEAR, 2017);
calendar.set(2022, Calendar.APRIL, 12);

2023-04-12 09:27 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/secondtask/Employee.java
> +public abstract class Employee implements Employable {
чутка перемудрил, можно было просто абстрактным классом ограничиться

2023-04-12 09:27 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/secondtask/CEO.java
> +    @Override
у тебя в трех классах одинаковые методы, зачем тогда они в этих классах а не в Employee?

2023-04-12 09:27 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/thirdtask/Register.java
> +    private ArrayList<Document> register = new ArrayList<>(10);
очень режет глаза) надо было делать через массивы, но если хотелось коллекции - тогда private List<Document> register = new ArrayList<>();

2023-04-12 20:03 UTC, Pavel-Tsishkevich requested changes

2023-04-12 20:03 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/SixthHomework.java
>      private static void documentFlow() {
мне не сильно нравится название метода, метод должен начинаться с глагола, а у тебя с существительного, подумай, может старт, ран, процесс или что еще подходит тут)

2023-04-12 20:03 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/secondtask/Employee.java
> +public abstract class Employee implements Employable{
видишь почему мне тут не нравится и то и другое, получается масло масляное, или в нашем случае Имплои Имплоиабле)

2023-04-12 20:03 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/secondtask/FinanceManager.java
>  public class FinanceManager extends Employee{
возникает вопрос - а какая теперь позиция у менеджера, если ты захочешь вызвать FinanceManager.getEmployeePosition)

2023-04-12 20:03 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/thirdtask/Register.java
> +    private List<Document> register = new ArrayList<>(10);
повторю - вот тут 10 не надо - new ArrayList<>(10); просто new ArrayList<>();

2023-04-12 20:19 UTC, Vagazzi commented on src/main/java/org/example/homework/sixth/thirdtask/Register.java
> +    private List<Document> register = new ArrayList<>(10);
Опять-таки, заданные условия

2023-04-12 20:19 UTC, Vagazzi commented on src/main/java/org/example/homework/sixth/secondtask/FinanceManager.java
>  public class FinanceManager extends Employee{
@Pavel-Tsishkevich FinanceManager
Логика в том, что его позиция - className().

2023-04-13 14:27 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/secondtask/FinanceManager.java
>  public class FinanceManager extends Employee{
@Vagazzi проблема в том, что несмотря на то, что ты можешь вызвать его название как class Name, методы которые ты объявил у родителя никуда не делись и работают не так, как ты от них ожидаешь

2023-04-13 14:28 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/thirdtask/Register.java
> +    private List<Document> register = new ArrayList<>(10);
@Vagazzi проблема в том, что 10 для ArrayList не является ограничением, он не мешает увеличить его до 20

2023-04-14 05:05 UTC, Pavel-Tsishkevich requested changes

2023-04-14 05:05 UTC, Pavel-Tsishkevich commented on src/main/java/org/example/homework/sixth/SixthHomework.java
> +        Employee ceo = new CEO("CEO");
Смотри, и мы вернулись к тому с чего начали) не надо говорить сео что он сео, он это знает (поэтому правильнее такое делать внутри конструктора по умолчанию)

2023-04-14 16:28 UTC, Pavel-Tsishkevich approved these changes

2023-04-14 17:10 UTC, merged